import type { Metadata } from "next";
import "./globals.css";
import { DigikalaContextProvider } from "@/components/context/DigikalaContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DigikalaContextProvider>
         {children}
        </DigikalaContextProvider>
      </body>
    </html>
  );
}
